{% set name = "slippers" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/slippers-{{ version }}.tar.gz
  sha256: 53b4ba40fd7495c1a24ff160de8a384aa90eaeb7615842e68f84455c387c4419

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7.0
  run:
    - django >=3.2
    - python >=3.7.0
    - pyyaml >=5.4.0
    - typeguard >=2.13.3,<3.0.0
    - typing_extensions >=4.4.0

test:
  imports:
    - slippers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://mitchel.me/slippers/
  dev_url: https://github.com/mixxorz/slippers
  summary: Build reusable components in Django without writing a single line of Python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
